name: On tag pushed
on:
  push:
    tags:
      - v*

  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout thermal_web
        uses: actions/checkout@v3

      # This part here is cloning a second repository
      # While cloning the repository:
      #   - it clones the repo into the given `path`
      #   - it checks out the branch defined at `ref`
      - name: Clone repo=geojson-data
        uses: actions/checkout@v3
        with:
          repository: llauner/geojson-data
          token: ${{ secrets.ACCESS_TOKEN }}
          path: ./geojson-data
          ref: master

      - name: Copy geojson data
        run: |
          cp ./geojson-data/*.zip ./geojson/
          
      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag eu.gcr.io/igc-flight-analysis/near_miss_web:latest
          
      - name: Push to Container registry
        uses: RafikFarhad/push-to-gcr-github-action@v4.1
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: eu.gcr.io
          project_id: igc-flight-analysis
          image_name: near_miss_web
          image_tag: latest
          push_only: true
          
  deploy-to-google-run:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCLOUD_SERVICE_KEY }}'

    - name: 'Deploy to Cloud Run: europe-west1'
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        image: 'eu.gcr.io/igc-flight-analysis/near_miss_web:latest'
        service: 'near-miss-web-run-app-europe-west1'
        region: 'europe-west1'
